### ISSUE TITLE
Context menu "open with" does not appear on Mac version

### ISSUE THREAD

**Issue by GeGerardo** [hhu-stups/camille#22]
The camille context menu does not appear in Rodin for Mac. I'm using OS X 10.11.3, Java 8 Build 73, tested in Rodin 3.2 and 3.1, Camille v 3.2.0.201511181037

**Comment by wysiib** [comment]
Which menu do you mean? The one with "open with" used to open a file in Camille?

**Comment by GeGerardo** [comment]
Yes :)

Em sexta-feira, 18 de março de 2016, Sebastian Krings <
notifications@github.com> escreveu:

**Comment by wysiib** [comment]
Is there no menu at all? Or is the Camille entry missing? If yes can you please send a screenshot of the menu you are seeing?

You can also try to execute Rodin with the "-consolelog" option set. Maybe the resulting output tells us something about the problem.

**Comment by GeGerardo** [comment]
Just CAmille entry is missing. Sorry to ask, but how can i set the consolelog? I tried put on executable rodin, but nothing happened
<img width="1280" alt="captura de tela 2016-03-18 as 09 56 18" src="https://cloud.githubusercontent.com/assets/17926153/13878720/ee3fbaec-ecf1-11e5-801c-378ded90e93e.png">

**Comment by wysiib** [comment]
You need to go to the directory you extracted the Rodin archive file to, and call
“./rodin -consolelog”.

Please send me any appearing error messages.

**Comment by GeGerardo** [comment]
Sorry for delay.

!SESSION 2016-03-18 11:52:04.964 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_65
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=pt_BR
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -consolelog

!ENTRY org.eventb.texteditor.parsers 4 0 2016-03-18 11:52:05.783
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eventb.texteditor.parsers [252]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eventb.texteditor.ui 4 0 2016-03-18 11:52:05.786
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eventb.texteditor.ui [253]
  Unresolved requirement: Require-Bundle: org.eventb.texttools; bundle-version="[3.1.0,3.3.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eventb.texttools; bundle-version="3.2.0.201511181037"; singleton:="true"
       org.eventb.texttools [254]
         Unresolved requirement: Require-Bundle: org.eventb.texteditor.parsers
           -> Bundle-SymbolicName: org.eventb.texteditor.parsers; bundle-version="3.2.0.201511181037"
              org.eventb.texteditor.parsers [252]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eventb.texttools 4 0 2016-03-18 11:52:05.789
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eventb.texttools [254]
  Unresolved requirement: Require-Bundle: org.eventb.texteditor.parsers
    -> Bundle-SymbolicName: org.eventb.texteditor.parsers; bundle-version="3.2.0.201511181037"
       org.eventb.texteditor.parsers [252]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by wysiib** [comment]
Judging by the exception, you are not using Java 8: java.version=1.6.0_65

Java 7 is required for Camille to work, hence you are seeing
Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

**Comment by GeGerardo** [comment]
So sorry about that. I forgot to setting java_home.
Thanks for help me.
PS: 
I found a real bug this time . Can i tell here or open a new issue ?

**Comment by wysiib** [comment]
No Problem :-)

Please open a new issue to avoid confusion.
